#!/bin/bash
set -e

WOWZA_VERSION=4.1.0
WOWZA_INSTALLER_URL="http://www.wowza.com/downloads/WowzaStreamingEngine-4-1-0/WowzaStreamingEngine-${WOWZA_VERSION}.deb.bin"

# download wowza installer
wget "${WOWZA_INSTALLER_URL}" -O WowzaStreamingEngine-${WOWZA_VERSION}.deb.bin

# disable user interaction during install
sed 's/^more <<"EOF"$/cat <<"EOF"/'                               -i WowzaStreamingEngine-${WOWZA_VERSION}.deb.bin
sed 's/^agreed=$/agreed=1/'                                       -i WowzaStreamingEngine-${WOWZA_VERSION}.deb.bin
sed 's/^ADMINUSER=$/ADMINUSER=admin/'                             -i WowzaStreamingEngine-${WOWZA_VERSION}.deb.bin
sed 's/\$ADMINUSER  \$ADMINPASS1 admin/\$ADMINUSER  admin admin/' -i WowzaStreamingEngine-${WOWZA_VERSION}.deb.bin
sed 's/^PWMATCH=$/PWMATCH=1/'                                     -i WowzaStreamingEngine-${WOWZA_VERSION}.deb.bin
sed 's/^VALIDLICKEY=$/VALIDLICKEY=1/'                             -i WowzaStreamingEngine-${WOWZA_VERSION}.deb.bin
sed 's/STARTSERVICES=$/STARTSERVICES=0/'                          -i WowzaStreamingEngine-${WOWZA_VERSION}.deb.bin

# install wowza streaming engine
chmod +x WowzaStreamingEngine-${WOWZA_VERSION}.deb.bin
./WowzaStreamingEngine-${WOWZA_VERSION}.deb.bin

# remove installer
rm -rf WowzaStreamingEngine-${WOWZA_VERSION}.deb.bin WowzaStreamingEngine-${WOWZA_VERSION}.deb

# move supervisord.log file to /var/log/wowza/supervisor/
sed 's|^logfile=.*|logfile=/var/log/wowza/supervisor/supervisord.log ;|' -i /etc/supervisor/supervisord.conf

# symlink /usr/local/WowzaStreamingEngine/logs -> /var/log/wowza/wowza
rm -rf /usr/local/WowzaStreamingEngine/logs
ln -sf /var/log/wowza/wowza /usr/local/WowzaStreamingEngine/logs

# configure supervisord to start wowza streaming engine
cat > /etc/supervisor/conf.d/wowza.conf <<EOF
[program:wowza]
priority=10
directory=/usr/local/WowzaStreamingEngine/bin
command=/usr/local/WowzaStreamingEngine/bin/startup.sh
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/wowza/supervisor/%(program_name)s.log
stderr_logfile=/var/log/wowza/supervisor/%(program_name)s.log
EOF

# configure supervisord to start wowza streaming engine manager
cat > /etc/supervisor/conf.d/wowzamgr.conf <<EOF
[program:wowzamgr]
priority=20
directory=/usr/local/WowzaStreamingEngine/manager/bin
command=/usr/local/WowzaStreamingEngine/manager/bin/startmgr.sh
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/wowza/supervisor/%(program_name)s.log
stderr_logfile=/var/log/wowza/supervisor/%(program_name)s.log
EOF

# configure supervisord to start crond
cat > /etc/supervisor/conf.d/cron.conf <<EOF
[program:cron]
priority=30
directory=/tmp
command=/usr/sbin/cron -f
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/wowza/supervisor/%(program_name)s.log
stderr_logfile=/var/log/wowza/supervisor/%(program_name)s.log
EOF

# configure supervisord log rotation
cat > /etc/logrotate.d/supervisord <<EOF
/var/log/wowza/supervisor/*.log {
  weekly
  missingok
  rotate 52
  compress
  delaycompress
  notifempty
  copytruncate
}
EOF

# configure wowza log rotation
cat > /etc/logrotate.d/wowza <<EOF
/var/log/wowza/wowza/*.log {
  weekly
  missingok
  rotate 52
  compress
  delaycompress
  notifempty
  copytruncate
}
EOF
